"""Notifier agent — sends results email to the candidate."""

from __future__ import annotations

import time
from datetime import UTC, datetime

import structlog

from job_hunter_agents.agents.base import BaseAgent
from job_hunter_agents.tools.email_sender import EmailSender
from job_hunter_core.state import PipelineState

logger = structlog.get_logger()

EMAIL_HTML_TEMPLATE = """\
<html>
<body>
<h2>Job Hunter Results</h2>
<p>Hi {name},</p>
<p>Your job search found <strong>{total_jobs}</strong> matches. \
Here are your top results:</p>

<table border="1" cellpadding="8" cellspacing="0" \
style="border-collapse:collapse;">
<tr style="background:#f0f0f0;">
<th>Rank</th><th>Score</th><th>Company</th>\
<th>Title</th><th>Location</th>
</tr>
{top_rows}
</table>

<p>Full results are attached as an Excel file.</p>
<p>Run ID: {run_id}<br>
Total scored: {total_jobs} | Above threshold: {above_threshold}</p>

<p style="color:#888;">Generated by Job Hunter Agent</p>
</body>
</html>
"""

EMAIL_TEXT_TEMPLATE = """\
Job Hunter Results

Hi {name},

Your job search found {total_jobs} matches.

Top results:
{top_text}

Full results are attached.

Run ID: {run_id}
"""


class NotifierAgent(BaseAgent):
    """Send results email to the candidate."""

    agent_name = "notifier"

    async def run(self, state: PipelineState) -> PipelineState:
        """Send email with results."""
        self._log_start()
        start = time.monotonic()

        if state.config.dry_run:
            logger.info("dry_run_skip_email")
            self._log_end(time.monotonic() - start)
            return state

        if not state.profile or not state.run_result:
            logger.warning("notifier_missing_profile_or_result")
            return state

        try:
            email_sent = await self._send_email(state)
            if state.run_result:
                state.run_result.email_sent = email_sent
        except Exception as e:
            self._record_error(state, e)

        self._log_end(time.monotonic() - start)
        return state

    async def _send_email(self, state: PipelineState) -> bool:
        """Build and send the results email."""
        profile = state.profile
        assert profile is not None

        today = datetime.now(UTC).strftime("%Y-%m-%d")
        subject = (
            f"[Job Hunter] {len(state.scored_jobs)} new matches "
            f"for {profile.current_title or 'your search'} — {today}"
        )

        top_jobs = state.scored_jobs[:5]
        top_rows = "\n".join(
            f"<tr><td>{sj.rank}</td><td>{sj.fit_report.score}</td>"
            f"<td>{sj.job.company_name}</td><td>{sj.job.title}</td>"
            f"<td>{sj.job.location or 'N/A'}</td></tr>"
            for sj in top_jobs
        )
        top_text = "\n".join(
            f"  {sj.rank}. [{sj.fit_report.score}] {sj.job.company_name} - {sj.job.title}"
            for sj in top_jobs
        )

        html_body = EMAIL_HTML_TEMPLATE.format(
            name=profile.name,
            total_jobs=len(state.scored_jobs),
            above_threshold=len(state.scored_jobs),
            top_rows=top_rows,
            run_id=state.config.run_id,
        )
        text_body = EMAIL_TEXT_TEMPLATE.format(
            name=profile.name,
            total_jobs=len(state.scored_jobs),
            top_text=top_text,
            run_id=state.config.run_id,
        )

        # Find xlsx attachment
        attachment = None
        if state.run_result and state.run_result.output_files:
            for f in state.run_result.output_files:
                if str(f).endswith(".xlsx"):
                    attachment = str(f)
                    break

        sender = EmailSender(
            provider=self.settings.email_provider,
            smtp_host=self.settings.smtp_host,
            smtp_port=self.settings.smtp_port,
            smtp_user=self.settings.smtp_user,
            smtp_password=(
                self.settings.smtp_password.get_secret_value()
                if self.settings.smtp_password
                else ""
            ),
            sendgrid_api_key=(
                self.settings.sendgrid_api_key.get_secret_value()
                if self.settings.sendgrid_api_key
                else ""
            ),
        )

        return await sender.send(
            to_email=str(profile.email),
            subject=subject,
            html_body=html_body,
            text_body=text_body,
            attachment_path=attachment,
        )
